name: build

on:
    push:
        branches:
            - master

jobs:
    first:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  package-name: examples_rclcpp_minimal_publisher
                  target-ros2-distro: humble
   
            
