name: build

on:
    push:
        branches:
            - master

jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: ros-tooling/setup-ros@v0.7
              with:
                  required-ros-distributions: humble
            - uses: ros-tooling/action-ros-ci@v0.3
              with:
                  package-name: minimal_publisher
                  target-ros2-distro: humble
   
            
