name: build

on:
    push:
        branches:
            - master

jobs:
    first:
        runs-on: macos-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run a one-liner
              run: echo "Hello, World!"
            - name: Run another one-liner
              run: |
               echo "Hello, World!"
               echo "This is a multi-line string"
    second:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Run a one-liner
              run: echo "Hello, World!"
            - name: Run another one-liner
              run: |
               echo "Hello, World!"
               echo "This is a multi-line string"
            
